# Generated by Django 5.1a1 on 2024-06-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=63)),
                ('city', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
            ],
        ),
    ]
