# Generated by Django 5.1a1 on 2024-07-01 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0003_remove_user_table_id_alter_user_table_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='password',
        ),
        migrations.AlterField(
            model_name='user_table',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
