# Generated by Django 5.1a1 on 2024-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0007_filerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='created_at',
        ),
    ]
