# Generated by Django 5.1a1 on 2024-07-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0010_filerecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerecord',
            name='user',
        ),
    ]
